env:
    PROJECT_SUBDIR: "."
    GODOT_HEADLESS_EXE: https://downloads.tuxfamily.org/godotengine/3.5/mono/Godot_v3.5-stable_mono_linux_headless_64.zip
    GODOT_EXPORT_TEMPLATES: https://downloads.tuxfamily.org/godotengine/3.5/mono/Godot_v3.5-stable_mono_export_templates.tpz


on:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: create game release
        uses: firebelley/godot-export@v3.0.0
        with:
          godot_executable_download_url: ${{ env.$GODOT_HEADLESS_EXE }}
          godot_export_templates_download_url: ${{ env.GODOT_EXPORT_TEMPLATES }}
          relative_project_path: ${{ env.PROJECT_SUBDIR }}
          generate_release_notes: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
