env:
    BUILD_WINDOWS: godot-mono-fps-tut-windows.zip
    BUILD_MACOS: godot-mono-fps-tut-macos.zip
    BUILD_LINUX: godot-mono-fps-tut-linux.zip
    ITCH_GAME_PAGE: godot-mono-fps-tutorial-series

on:
  release:
    types: [published]
jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "$BUILD_WINDOWS"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: "$ITCH_GAME_PAGE"
          ITCH_USER: queenofsquiggles
          PACKAGE: "$BUILD_WINDOWS"
          VERSION: ${{ steps.download-windows.outputs.version }}
  release_macos:
    runs-on: ubuntu-latest
    steps:
      - name: download MacOS
        id: download-macos
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: "$BUILD_MACOS"
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (MacOS)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: "$ITCH_GAME_PAGE"
          ITCH_USER: queenofsquiggles
          PACKAGE: "$BUILD_MACOS"
          VERSION: ${{ steps.download-macos.outputs.version }}
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: "$BUILD_LINUX"
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Linux)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: "$ITCH_GAME_PAGE"
          ITCH_USER: queenofsquiggles
          PACKAGE: "$BUILD_LINUX"
          VERSION: ${{ steps.download-linux.outputs.version }}
