on:
  release:
    types: [published]
jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@main
        with:
          file: godot-mono-fps-tut-windows.exe
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@main
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: godot-mono-fps-tutorial-series
          ITCH_USER: queenofsquiggles
          PACKAGE: godot-mono-fps-windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
  release_macos:
    runs-on: ubuntu-latest
    steps:
      - name: download MacOS
        id: download-macos
        uses: dsaltares/fetch-gh-release-asset@main
        with:
          version: "latest"
          file: godot-mono-fps-tut-macos.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (MacOS)
        uses: josephbmanley/butler-publish-itchio-action@main
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: godot-mono-fps-tutorial-series
          ITCH_USER: queenofsquiggles
          PACKAGE: godot-mono-fps-mac.zip
          VERSION: ${{ steps.download-macos.outputs.version }}
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@main
        with:
          version: "latest"
          file: godot-mono-fps-tut-linux.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Linux)
        uses: josephbmanley/butler-publish-itchio-action@main
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: godot-mono-fps-tutorial-series
          ITCH_USER: queenofsquiggles
          PACKAGE: godot-mono-fps-linux.zip
          VERSION: ${{ steps.download-linux.outputs.version }}
